language: python
dist: xenial
python:
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install -e .
# command to run tests
script:
  - pytest --cov metakb --cov-report term-missing
  - flake8
after_success:
  - coveralls
