language: python
dist: xenial
python:
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install -e .
# command to run tests
script:
  - pytest
  - git diff-tree --no-commit-id --name-only -r $REVISION | xargs pre-commit run --files
after_success:
  - coveralls
